analytics: {}
color:
  brandColors: []
  brandStrength: 0.875
  lightness: 0.849662
  rhythmicContrast: 0.193412
  saturation: 0.205236
cta: {}
layout_spectrum: 0.938344
name: Ninja-Dojo
opengraph: {}
purpose:
  - name: sign-ups
typography_spectrum: 0.674831
